# Numpy习题

In [5]:
import numpy as np

## 1. 用多种方法创建一个 3x3 并且值从0到8的矩阵

In [40]:
#第一种
Z = np.arange(9).reshape(3,3)
print(Z)


#第二种
k=np.array([(0, 1, 2),(3, 4, 5),(6,7,8)])
k


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 2. 用2种创建一个 10x10 的随机数组

In [22]:
#第一种
k = np.random.randint(1,20,(10,10))
k

#第二种
z = np.random.random((10,10))
z


array([[0.12898538, 0.99999465, 0.06378569, 0.60020749, 0.58508535,
        0.06118953, 0.56676751, 0.10901185, 0.2969943 , 0.13063407],
       [0.92943178, 0.61758537, 0.31584417, 0.50088812, 0.98117722,
        0.73555578, 0.16636216, 0.3032065 , 0.77149029, 0.50214648],
       [0.08739372, 0.43013459, 0.96111727, 0.65013675, 0.8597506 ,
        0.56559216, 0.0118121 , 0.38441137, 0.04891694, 0.02034067],
       [0.18343347, 0.85974129, 0.11191143, 0.81101335, 0.13385942,
        0.29821302, 0.87886393, 0.540864  , 0.21905982, 0.81577282],
       [0.74132863, 0.20361475, 0.73227621, 0.10680705, 0.10364364,
        0.79213245, 0.53193385, 0.01981982, 0.9875845 , 0.68046884],
       [0.64737529, 0.16511631, 0.31227148, 0.52878346, 0.61531362,
        0.94902323, 0.29494911, 0.86774711, 0.47603249, 0.48444582],
       [0.59127652, 0.66735143, 0.17149738, 0.99392687, 0.64688482,
        0.07801723, 0.52467241, 0.97037619, 0.45969321, 0.93877583],
       [0.48078547, 0.50377663, 0.6104861

## 3. 创建一个 5x5的矩阵，并设置值1,2,3,4,5落在其对角线下方位置 

In [32]:
a=np.diag(np.arange(1,5),k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

## 4. 用随机数函数创建一个长度为10的一维数组，并将其排序

In [109]:
arr= np.random.randint(1,100,10)
arr
np.sort(arr)

array([ 7, 12, 18, 23, 39, 47, 51, 53, 59, 79])

## 5.切取数组arr4中四个角的元素并保持和原数组相同的形状 

In [48]:
arr4 = np.array([[0,  1,  2],[3,  4,  5],[6,  7,  8],[9,  10,  11]])
arr4


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [86]:
a=np.array([[0,0,3,3]])
b=np.array([[0,2,0,2]])
c=arr4[a,b].reshape((2,2))
c






array([[ 0,  2],
       [ 9, 11]])

## 6. 从arr10中切取元素5出来

In [89]:
arr10 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

k=arr10[1:2,1:2]

k


array([[5]])

## 7. 从arr10中切取1,2,4,5,7,8出来

In [92]:
arr10 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

arr10

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [95]:
k=arr10[0:3,0:2]

k

array([[1, 2],
       [4, 5],
       [7, 8]])

## 8. 从arr5中切取元素取值大于arr5所有元素均值的元素

In [113]:
arr5 = np.random.randint(100,size = (4,4))

In [100]:
print(arr5)

[[47 30 13 58]
 [95 16 75 24]
 [78 96 56 90]
 [88 95 24 27]]


In [116]:
arr5[arr5>arr5.mean()]


array([71, 90, 58, 85, 78, 68, 75, 77, 82])

## 9. 求arr5中所有元素的平方

In [6]:
arr5 = np.arange(15).reshape(3,5) 
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
display(arr5*arr5)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

## 10 求arr4中元素的最小值,并分别求出按不同轴计算出的最大值、最小值、平均值;

In [10]:
arr4 = np.array([[75, 27,  6,  2],
       [ 3, 67, 76, 48],
       [22, 49, 52,  5],
       [13, 89, 34, 75]])

In [12]:
#最小值
arr4.min()

#按行
#最大值
arr4.max(axis=1)
#最小值
arr4.min(axis=1)
#平均值
arr4.mean(axis=1)

#按列

#最大值
arr4.max(axis=0)
#最小值
arr4.min(axis=0)

#平均值
arr4.mean(axis=0)

array([ 2,  3,  5, 13])

## 11. 对arr4中的元素进行去重操作

In [13]:
arr4 = np.array([[75, 27,  6,  2],
       [ 3, 67, 76, 48],
       [22, 49, 52,  5],
       [13, 89, 34, 75]])

In [14]:
#去重  np.unique(arr4)

array([ 2,  3,  5,  6, 13, 22, 27, 34, 48, 49, 52, 67, 75, 76, 89])

## 12. 分别按照不同轴对arr4中的元素进行排序

In [15]:
arr4 = np.array([[75, 27,  6,  2],
       [ 3, 67, 76, 48],
       [22, 49, 52,  5],
       [13, 89, 34, 75]])

In [19]:
np.sort(arr4,axis=1)


np.sort(arr4,axis=0)


array([[ 2,  6, 27, 75],
       [ 3, 48, 67, 76],
       [ 5, 22, 49, 52],
       [13, 34, 75, 89]])

## 13切取arr5中的第0行元素赋值给arr6,并保证这两个数组完全独立,改变arr6中第2个元素为6,查看arr5是否有变化

In [71]:
arr5 = np.arange(15).reshape(3,5) 
arr5




array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [72]:
arr6=arr5[0:1,0:5]
arr6

array([[0, 1, 2, 3, 4]])

In [78]:
arr6[0,1] = 6
arr6

arr5
#arr5 有变化

array([[ 0,  6,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 14.判断arr7中是否全部是空值,并对arr7中的元素求平均数

In [79]:
arr7 = np.array([np.nan,3.14,np.nan,3,14,2,np.nan]) 

In [80]:
#判断是否为空值
np.isnan(arr7)

array([ True, False,  True, False, False, False,  True])

In [81]:
#求平均数
np.nanmean(arr7)

5.535

## 15 有下列三个数组：arr2、arr3、arr4。分别查看这三个数组的形状\维度\元素个数\元素数据类型

In [82]:
arr2 = np.random.randn(3,)
arr3 = np.random.randn(3,4)
arr4 = np.random.randn(1,3,4)

In [91]:
#arr2

print("数组元素数据类型：",arr2.dtype) 
print("数组元素总数：",arr2.size)     
print("数组形状：",arr2.shape)         
print("数组的维度数目",arr2.ndim)


数组元素数据类型： float64
数组元素总数： 3
数组形状： (3,)
数组的维度数目 1


In [88]:
#arr3

print("数组元素数据类型：",arr3.dtype) 
print("数组元素总数：",arr3.size)       
print("数组形状：",arr3.shape)        
print("数组的维度数目",arr3.ndim)

数组元素数据类型： float64
数组元素总数： 12
数组形状： (3, 4)
数组的维度数目 2


In [89]:
#arr4

print("数组元素数据类型：",arr4.dtype)  
print("数组元素总数：",arr4.size)      
print("数组形状：",arr4.shape)        
print("数组的维度数目",arr4.ndim)

数组元素数据类型： float64
数组元素总数： 12
数组形状： (1, 3, 4)
数组的维度数目 3


## 16 把arr4拆分为左右两部分，左边2列

In [96]:
arr4 = np.random.randint(20,size = (4, 5))
arr4

array([[ 5,  3, 16, 19, 15],
       [ 6, 18, 15,  5, 10],
       [17,  4, 11,  2, 14],
       [ 6, 13,  2, 16, 10]])

In [99]:
l=np.hsplit(arr4,[2])
l


[array([[ 5,  3],
        [ 6, 18],
        [17,  4],
        [ 6, 13]]),
 array([[16, 19, 15],
        [15,  5, 10],
        [11,  2, 14],
        [ 2, 16, 10]])]

## 17. 将下面两个数组分别按照最外边的轴和最里边的轴进行拼接

In [100]:
arr5 = np.arange(15).reshape(3,5)
arr6 = np.arange(20,35).reshape(3,5)

In [101]:

np.hstack((arr5,arr6)) 

array([[ 0,  1,  2,  3,  4, 20, 21, 22, 23, 24],
       [ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

In [102]:
np.vstack((arr5,arr6)) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

## 18 任意写两个形状不同但是符合广播规则的数组,并对他们包含的元素进行乘法运算

In [107]:
k1=np.random.randint(1,30,(1,6))
k2=np.random.randint(1,30,(4,6))

display(k1*k2)

array([[357, 176, 702, 260,  80, 319],
       [306,  22, 162, 260,  12, 198],
       [255,  99, 324, 364,  80, 176],
       [153, 121, 270,  52,  64, 275]])